repos:
  - repo: local
    hooks:
    - id: update-requirements-txt
      name: update-requirements-txt
      description: 'Generate requirements.txt based on poetry.lock'
      entry: bash -c 'poetry export --without-hashes --format "requirements.txt" --output "requirements.txt"'
      language: system
      pass_filenames: false

  - repo: local
    hooks:
    - id: update--dev-requirements-txt
      name: update--dev-requirements-txt
      description: 'Generate requirements-dev.txt based on poetry.lock'
      entry: bash -c 'poetry export --dev --without-hashes --format "requirements.txt" --output "requirements-dev.txt"'
      language: system
      pass_filenames: false

  # Check for hardcoded passwords, keys, tokens
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.5.0
    hooks:
      - id: gitleaks

  # convert app/core/templates/markdown/*.html to app/core/templates/markdown/*.md
  # Please make sure you have pandoc installed (sudo apt install pandoc)
  - repo: local
    hooks:
    - id: convert-core-md-to-html
      name: convert-core-md-to-html
      description: 'convert app/core/markdown/*.md to app/core/markdown/*.html'
      entry: bash -c 'pandoc -o app/core/templates/markdown/*.html app/core/templates/markdown/*.md'
      language: system
      pass_filenames: false

  # convert app/blog/templates/markdown/*.md to app/blog/templates/markdown/*.html
  # Please make sure you have pandoc installed (sudo apt install pandoc)
  - repo: local
    hooks:
    - id: convert-blog-md-to-html
      name: convert-blog-md-to-html
      description: 'convert app/blog/markdown/*.md to app/blog/markdown/*.html'
      entry: bash -c 'pandoc -o app/blog/templates/markdown/*.html app/blog/templates/markdown/*.md'
      language: system
      pass_filenames: false

  # Create base links for the blog
  # Please make sure tree is installed (sudo apt install tree)
  - repo: local
    hooks:
    - id: create-blog-base-page
      name: create-blog-base-page
      description: 'Create the base links for the blog home page based on files inside app/blog/templates/markdown/'
      entry: bash -c 'cd app/blog/templates/markdown/ && tree -H 'https://isuru.ca/blog' --noreport --charset utf-8 -P "*.html" -I "blog_index.html" -o ../blog_index.html'
      language: system
      pass_filenames: false