steps:
- name: python:3.8
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'requirements/dev.txt'
- name: python:3.8
  entrypoint: flake8
  id: RUN-LINTER-CHECK
  waitFor:
  - INSTALL