steps:
- name: python:3.8
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'requirements-dev.txt'

- name: python:3.8
  entrypoint: python3
  id: RUN-LINTER-CHECK
  args:
  - '-m'
  - 'flake8'
  - '--append-config'
  - '.setup.cfg'
  - 'app/'
  - 'main.py'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: python3
  id: RUN-BANDIT-SECURITY-CHECK
  args:
  - '-m'
  - 'bandit'
  - '-r'
  - 'app/'
  - 'main.py'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: python3
  id: RUN-SAFETY-PROD-CHECK
  args:
  - '-m'
  - 'safety'
  - 'check'
  - '-r'
  - 'requirements.txt'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: python3
  id: RUN-SAFETY-DEV-CHECK
  args:
  - '-m'
  - 'safety'
  - 'check'
  - '-r'
  - 'requirements-dev.txt'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: python3
  id: RUN-PYTEST
  args:
  - '-m'
  - 'coverage'
  - 'run'
  - '-m'
  - 'pytest'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: python3
  id: RUN-COVERAGE
  args:
  - '-m'
  - 'coverage'
  - 'report'
  - '--fail-under=80'
  waitFor:
  - RUN-PYTEST