steps:
- name: python:3.8
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r'
  - 'requirements/dev.txt'
  
- name: python:3.8
  entrypoint: python3
  id: RUN-LINTER-CHECK
  args:
  - '-m'
  - 'flake8'
  - '--append-config'
  - '.flake8'
  - 'app/'
  - 'main.py'
  waitFor:
  - INSTALL

- name: python:3.8
  entrypoint: bash
  id: RUN-BANDIT-SECURITY-CHECK
  args:
  - '-c'
  - 'python3'
  - '-m'
  - 'bandit'
  - '-r'
  - 'app/'
  - 'main.py'
  waitFor:
  - INSTALL